language: go
before_install:
- openssl aes-256-cbc -K $encrypted_0ccecc354d41_key -iv $encrypted_0ccecc354d41_iv
  -in dokku-deployment.key.enc -out dokku-deployment.key -d
after_success:
- eval $(ssh-agent -s)
- chmod 600 .travis/dokku-deployment.key
- ssh-add .travis/dokku-deployment.key
- ssh-keyscan apps.espe.tech >> ~/.ssh/known_hosts
- git remote add dokku dokku@apps.espe.tech
- git config --global push.default simple
- git push dokku master